services:
  - type: web
    name: futurproctor
    env: python
    plan: free                 # <--- THIS ENSURES $0 COST
    
    # FIX: Use 'rootDir', not 'rootDirectory'
    rootDir: sih-proctor-main/futurproctor
    
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn futurproctor.wsgi:application
    plan: standard
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10