services:
  - type: web
    name: futurproctor
    env: python
    plan: free                 # <--- THIS ENSURES $0 COST
    
    # FIX: Use 'rootDir', not 'rootDirectory'
    rootDir: sih-proctor-main/futurproctor
    
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn futurproctor.wsgi:application
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10