services:
  - type: web
    name: sih-proctor-2
    env: python
    rootDirectory: futurproctor  # Sets the working folder
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn futurproctor.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10